### ISSUE TITLE
NEUItemEntryRenderer crashes when it gets to drills

### ISSUE THREAD

**Issue by SteptimusHeap** [romangraef/Firmament#4]
The fuel trips them up real bad, it tries to read the formatting codes as part of the number:
```java.lang.NumberFormatException: For input string: "7 230008"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at net.minecraft.class_332.betterinject$blg000$skyblocker$renderItemBar(class_332.java:1789)
	at net.minecraft.class_332.method_51432(class_332.java)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderOverlay(ItemEntryDefinition.java:348)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.render(ItemEntryDefinition.java:283)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:183)
	at moe.nea.firmament.rei.NEUItemEntryRenderer.render(NEUItemEntryRenderer.kt:26)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:183)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:427)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:383)
	at me.shedaniel.rei.impl.client.gui.widget.MergedWidget.method_25394(MergedWidget.java:50)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.method_25394(DelegateWidgetWithTranslate.java:58)
	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25394(DefaultDisplayViewingScreen.java:336)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)```
	
	```Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: prismarine_shard
	Item Damage: 0
	Item NBT: {AttributeModifiers:[],Enchantments:[{}],ExtraAttributes:{drill_fuel:3000.0d,enchantments:{},id:"TITANIUM_DRILL_2",modifier:'originTag:"UNKNOWN"'},HideFlags:254.0d,display:{Lore:['{"text":"§8Breaking Power 8"}','{"text":""}','{"text":"§7Damage: §c+75"}','{"text":"§7Mining Speed: §a+900"}','{"text":"§7Mining Fortune: §a+40"}','{"text":" §8[§7⸕§8]"}','{"text":""}','{"text":"§7Fuel Tank: §cNot Installed"}','{"text":"§7§7Increases fuel capacity with"}','{"text":"§7part installed."}','{"text":""}','{"text":"§7Drill Engine: §cNot Installed"}','{"text":"§7§7Increases §6⸕ Mining Speed"}','{"text":"§6§7with part installed."}','{"text":""}','{"text":"§7Upgrade Module: §cNot Installed"}','{"text":"§7§7Applies a passive upgrade with"}','{"text":"§7part installed."}','{"text":""}','{"text":"§7Apply Drill Parts to this Drill"}','{"text":"§7by talking to a §2Drill"}','{"text":"§2Mechanic§7!"}','{"text":""}','{"text":"§7Fuel: §23,000§8/3k"}','{"text":""}','{"text":"§7§8This item can be reforged!"}','{"text":"§7§4❣ §cRequires §5Heart of the"}','{"text":"§5Mountain Tier 5§c."}','{"text":"§5§lEPIC DRILL"}'],Name:'{"text":"§5Titanium Drill DR-X455"}'},overrideMeta:1b}
	Item Foil: true```

**Comment by SteptimusHeap** [comment]
forgot to include `java.lang.NumberFormatException: For input string: "7 230008"`

**Comment by romangraef** [comment]
This is a bug in skyblocker (https://github.com/SkyblockerMod/Skyblocker/issues/258). disable or update skyblocker.
